server.port: 80
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    drop-first: true